name: Bump version
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Create tag if bumped
      uses: ./.github/actions/tag_repo
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      id: tag_repo

