name: Bump version
on:
  push:
    branches:
      - tag-action

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Hello world action step
      uses: ./.github/actions/tag_repo
      id: tag_repo
      with:
        who-to-greet: 'Mona the Octocat'

    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
