name: Publish to Github Pages

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - main
jobs:
  generateDocs:
    name: Generate project documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Setup Beam"
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.17.0'
          otp-version: '26.0'

      - name: "Install dependencies"
        run: mix deps.get

      - name: "Generates documentation"
        run: mix docs

      - name: "Setup Pages"
        uses: actions/configure-pages@v3

      - name: "Upload artifact"
        uses: actions/upload-pages-artifact@v3
        with:
          path: doc/

      - name: "Deploy to GitHub Pages"
        id: deployment
        uses: actions/deploy-pages@v4
